name: Installation and Setup Check

on:
  push:
    branches: [main]

jobs:
  installation-and-setup-check:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: install chezmoi
        run: brew install chezmoi

      - name: check brew tap, brew and cask package installation
        run: |
          grep -Ev "awscli|cocoapods" dot_Brewfile > /tmp/dotfiles.Brewfile.ci
          brew bundle --verbose --file=/tmp/dotfiles.Brewfile.ci

      - name: check chezmoi source state
        run: chezmoi --source=. apply --dry-run --verbose
